[daterange]
start_date=2025-10-01
end_date=2026-04-01

[dirpath]
out=out/
in=data/

[data]
sa22019=src/data/SA22019_TA2019_WARD2019.json

# by convertion, clean is the processed name

[data.airbnb]
raw=listings_combined.csv
clean=listings_combined_cleaned.csv
[data.bonds]
raw=Detailed-Quarterly-Tenancy-Q1-2020-Q3-2026.csv
clean=Detailed-Quarterly-Tenancy-Q1-2020-Q3-2026_cleaned.csv
[data.reviews.monthly_results]
clean=highest_reviews_monthly_results.csv
[data.reviews.figure.number]
clean=highest_number_of_airbnb_reviews_in_christchurch
[data.reviews.figure.topten]
clean=top_10_percent_number_of_reviews_cutoff_in_christchurch
[data.reviews.figure.toptwenty]
clean=top_20_christchurch_airbnb_properties
[data.reviews.figure.highest]
clean=highest_number_of_airbnb_reviews_in_christchurch 

[listings]
names=listings_oct.csv listings_nov.csv listings_dec.csv listings_jan.csv listings_feb.csv listings_mar.csv listings_apr.csv listings_may.csv listings_jun.csv
dates=2025-10-01 2025-11-01 2025-12-01 2026-01-01 2026-02-01 2026-03-01 2026-04-01 2026-05-01 2026-06-01

[api]
key=
